export type Category = {
  id: string;
  label: string;
  color: string;
};

export type Idea = {
  categoryId: string;
  title: string;
  pitch: string;
  buyer: string;
  model: string;
  modelId: string;
  fit: string;
};

export const categories: Category[] = [
  { id: "food", label: "Food", color: "#C9A227" },
  { id: "home", label: "Home", color: "#5B9E3F" },
  { id: "money", label: "Money", color: "#2E9E8F" },
  { id: "car", label: "Car", color: "#C0453F" },
  { id: "health", label: "Health", color: "#4F6BED" },
  { id: "pets", label: "Pets", color: "#C2683A" },
  { id: "style", label: "Style", color: "#B4478F" },
  { id: "creator", label: "Creator", color: "#7C5CFF" },
  { id: "work", label: "Work", color: "#3E7CC4" },
  { id: "learning", label: "Learning", color: "#4A8FA8" },
  { id: "nostalgia", label: "Nostalgia", color: "#8A5CC4" },
  { id: "chaos", label: "Chaos", color: "#6B7280" },
];

export const ideas: Idea[] = [
  {
    categoryId: "food",
    title: "Fridge Roulette",
    pitch: "Photograph what is actually in your fridge, get dinner you can make tonight.",
    buyer: "Grocery chains and meal-kit apps",
    model: "Qwen3.5-4B, the small current vision model",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "food",
    title: "Menu Decoder",
    pitch: "Photograph a menu you cannot read, see what the dishes actually are.",
    buyer: "Travel apps and tourist restaurants",
    model: "Qwen3.5-4B, reads text in images natively",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "food",
    title: "Receipt Roast",
    pitch: "Scan a grocery receipt, find out exactly what you overpaid for.",
    buyer: "Budgeting and cashback apps",
    model: "PP-DocLayoutV3 for structure, then a small model to judge",
    modelId: "PaddlePaddle/PP-DocLayoutV3_safetensors",
    fit: "about 100MB",
  },

  {
    categoryId: "home",
    title: "Plant Doctor",
    pitch: "Photograph a dying plant, get the diagnosis and the fix before it is too late.",
    buyer: "Nurseries, plant shops, and gardeners",
    model: "Qwen3.5-4B against the abandoned plant-disease classifiers",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "home",
    title: "What Is This Bug",
    pitch: "Photograph the insect on your wall, learn if it is harmless or an infestation.",
    buyer: "Pest control companies",
    model: "SigLIP2 zero-shot against a list of species names",
    modelId: "google/siglip2-giant-opt-patch16-384",
    fit: "3.7GB once cast to fp16",
  },
  {
    categoryId: "home",
    title: "Fix It Yourself",
    pitch: "Photograph the broken thing, get the repair steps and the parts list.",
    buyer: "Hardware stores and home warranty firms",
    model: "Qwen3.5-4B plus MiniLM retrieval over manuals",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },

  {
    categoryId: "money",
    title: "Thrift Flip",
    pitch: "Photograph a thrift store find, get what it actually sells for online.",
    buyer: "Resellers and marketplace apps",
    model: "CLIP embeddings matched against live listings",
    modelId: "openai/clip-vit-large-patch14",
    fit: "under 1GB",
  },
  {
    categoryId: "money",
    title: "Subscription Purge",
    pitch: "Feed a bank statement, surface every subscription you forgot you pay for.",
    buyer: "Neobanks and budgeting apps",
    model: "Qwen3-0.6B, small enough that the margins actually work",
    modelId: "Qwen/Qwen3-0.6B",
    fit: "1.5GB — leaves the card almost free",
  },
  {
    categoryId: "money",
    title: "Denial Decoder",
    pitch: "Feed an insurance denial letter, get the appeal that actually cites the policy.",
    buyer: "Patients, clinics, and patient advocates",
    model: "Qwen3.5-9B for the long-context reading",
    modelId: "QuantTrio/Qwen3.5-9B-AWQ",
    fit: "11.5GB even quantized — nothing else fits beside it",
  },

  {
    categoryId: "car",
    title: "Engine Ear",
    pitch: "Record the noise your car makes, get the problem before the mechanic quotes you.",
    buyer: "Drivers and independent repair shops",
    model: "CLAP, which matches sounds to text descriptions zero-shot",
    modelId: "laion/clap-htsat-fused",
    fit: "under 1GB",
  },
  {
    categoryId: "car",
    title: "Dent Estimator",
    pitch: "Photograph the damage, get the estimate the body shop would have given you.",
    buyer: "Insurers and body shops",
    model: "CLIPSeg to outline the damage, then a model to price it",
    modelId: "CIDAS/clipseg-rd64-refined",
    fit: "under 1GB",
  },
  {
    categoryId: "car",
    title: "Warning Light Decoder",
    pitch: "Photograph the light on your dash, learn if you can keep driving or need to stop.",
    buyer: "Roadside assistance and insurers",
    model: "Qwen3.5-4B",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },

  {
    categoryId: "health",
    title: "Lab Report Translator",
    pitch: "Turn bloodwork into plain English and the questions worth asking your doctor.",
    buyer: "Clinics fielding the follow-up calls",
    model: "Qwen3.5-9B",
    modelId: "QuantTrio/Qwen3.5-9B-AWQ",
    fit: "11.5GB even quantized — nothing else fits beside it",
  },
  {
    categoryId: "health",
    title: "Form Check",
    pitch: "Film a lift, get told which joint is about to get hurt.",
    buyer: "Gyms and physical therapists",
    model: "MediaPipe Pose, the only pose model still maintained",
    modelId: "qualcomm/MediaPipe-Pose-Estimation",
    fit: "Tiny, runs realtime",
  },
  {
    categoryId: "health",
    title: "Sleep Sounds",
    pitch: "Record a night of sleep, find out whether you actually stopped breathing.",
    buyer: "Sleep clinics and wearable companies",
    model: "AST, trained on 527 everyday sound classes",
    modelId: "MIT/ast-finetuned-audioset-10-10-0.4593",
    fit: "about 350MB",
  },

  {
    categoryId: "pets",
    title: "Dog Translator",
    pitch: "Record the barking, get what the dog is actually trying to tell you.",
    buyer: "Pet apps and training services",
    model: "CLAP, prompted with what each bark might mean",
    modelId: "laion/clap-htsat-fused",
    fit: "under 1GB",
  },
  {
    categoryId: "pets",
    title: "Vet Or Wait",
    pitch: "Photograph the lump on your pet, learn if it is an emergency tonight.",
    buyer: "Pet insurers and telehealth vets",
    model: "Qwen3.5-4B, since every specialist vet model is abandoned",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "pets",
    title: "Shelter Guess",
    pitch: "Photograph a shelter dog, get the breed mix and a real age estimate.",
    buyer: "Shelters and adoption sites",
    model: "SigLIP2 zero-shot versus a breed classifier with 1,700 downloads",
    modelId: "google/siglip2-giant-opt-patch16-384",
    fit: "3.7GB once cast to fp16",
  },

  {
    categoryId: "style",
    title: "Dupe Finder",
    pitch: "Photograph any piece of clothing, find the version that costs a fifth as much.",
    buyer: "Shopping and cashback apps",
    model: "Fashion-CLIP, trained specifically on clothing",
    modelId: "patrickjohncyh/fashion-clip",
    fit: "under 1GB",
  },
  {
    categoryId: "style",
    title: "Closet Match",
    pitch: "Photograph your closet once, get outfits built only from what you own.",
    buyer: "Retail apps and stylists",
    model: "SegFormer clothes parsing, then Fashion-CLIP to match",
    modelId: "mattmdjaga/segformer_b2_clothes",
    fit: "about 100MB",
  },
  {
    categoryId: "style",
    title: "Fit Check",
    pitch: "Photograph the outfit, get scored and roasted before you leave the house.",
    buyer: "Fashion apps and social platforms",
    model: "Qwen3.5-4B",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },

  {
    categoryId: "creator",
    title: "Clip Finder",
    pitch: "Turn a two hour recording into the four clips actually worth posting.",
    buyer: "Podcasters and marketing teams",
    model: "Whisper large-v3-turbo, then a small model to pick moments",
    modelId: "openai/whisper-large-v3-turbo",
    fit: "1.5GB — runs alongside anything",
  },
  {
    categoryId: "creator",
    title: "Voice Double",
    pitch: "Clone your voice once, fix a flubbed line without recording it again.",
    buyer: "Creators, dubbing studios, and audiobook narrators",
    model: "Qwen3-TTS CustomVoice, released this year",
    modelId: "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
    fit: "4.2GB",
  },
  {
    categoryId: "creator",
    title: "Thumbnail Tester",
    pitch: "Upload ten thumbnails, get told which one actually gets the click.",
    buyer: "Creators and agencies",
    model: "CLIP, scoring each frame against what a viewer wants",
    modelId: "openai/clip-vit-large-patch14",
    fit: "under 1GB",
  },

  {
    categoryId: "work",
    title: "Call To Job Ticket",
    pitch: "Record the customer call, get a ticket with the address and the parts.",
    buyer: "Plumbers, electricians, and HVAC shops",
    model: "Whisper turbo plus pyannote to tell the speakers apart",
    modelId: "pyannote/speaker-diarization-community-1",
    fit: "under 1GB — pairs with Whisper",
  },
  {
    categoryId: "work",
    title: "Decisions Not Transcripts",
    pitch: "Turn a meeting recording into decisions and owners, not forty pages of text.",
    buyer: "Any team that runs too many meetings",
    model: "Qwen3-ASR-1.7B, this year's speech model",
    modelId: "Qwen/Qwen3-ASR-1.7B",
    fit: "4.4GB",
  },
  {
    categoryId: "work",
    title: "Handwriting Rescue",
    pitch: "Photograph messy handwritten field notes, get clean structured text.",
    buyer: "Field crews, clinics, and inspectors",
    model: "Qwen3.5-4B, which beats the OCR specialists on handwriting",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },

  {
    categoryId: "learning",
    title: "Show The Steps",
    pitch: "Photograph a math problem, get the working out instead of just the answer.",
    buyer: "Parents and tutoring apps",
    model: "Qwen3.5-4B",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "learning",
    title: "Accent Coach",
    pitch: "Read a sentence out loud, hear exactly which sounds gave you away.",
    buyer: "Language learning apps",
    model: "Whisper large-v3-turbo with timestamps",
    modelId: "openai/whisper-large-v3-turbo",
    fit: "1.5GB — runs alongside anything",
  },
  {
    categoryId: "learning",
    title: "Textbook To Flashcards",
    pitch: "Photograph the pages, get cards that test what you actually missed.",
    buyer: "Students and study apps",
    model: "PP-DocLayoutV3 to read pages, Qwen3-0.6B to write cards",
    modelId: "PaddlePaddle/PP-DocLayoutV3_safetensors",
    fit: "about 100MB",
  },

  {
    categoryId: "nostalgia",
    title: "Photo Revival",
    pitch: "Restore a water-damaged family photo from thirty years ago.",
    buyer: "Photo services and families",
    model: "Real-ESRGAN, the tool that actually does this",
    modelId: "Comfy-Org/Real-ESRGAN_repackaged",
    fit: "60MB — barely touches the GPU",
  },
  {
    categoryId: "nostalgia",
    title: "Recipe Cards",
    pitch: "Photograph a grandmother's handwritten recipe cards, get them cookable.",
    buyer: "Families and recipe apps",
    model: "Qwen3.5-4B reading the handwriting",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "nostalgia",
    title: "Voice Time Capsule",
    pitch: "Take thirty seconds of an old recording and hear that voice speak again.",
    buyer: "Anyone with a box of old tapes",
    model: "Qwen3-TTS CustomVoice, cloning from a short sample",
    modelId: "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",
    fit: "4.2GB",
  },

  {
    categoryId: "chaos",
    title: "Is This Edible",
    pitch: "Photograph the mushroom, get a confidence score and a very serious warning.",
    buyer: "Foragers, and lawyers afterwards",
    model: "SigLIP2 zero-shot versus a classifier with 124 downloads",
    modelId: "google/siglip2-giant-opt-patch16-384",
    fit: "3.7GB once cast to fp16",
  },
  {
    categoryId: "chaos",
    title: "Roast My Camera Roll",
    pitch: "Feed it a month of your photos, get judged on how you spend your life.",
    buyer: "Nobody. That is the point.",
    model: "Qwen3.5-4B",
    modelId: "Qwen/Qwen3.5-4B",
    fit: "8.7GB in fp16 — fills most of the card",
  },
  {
    categoryId: "chaos",
    title: "Under One Billion",
    pitch: "Solve any of these for real with a model small enough to run on a laptop.",
    buyer: "Anyone who needs the margins to work",
    model: "Qwen3-0.6B, 28 million downloads and almost free to run",
    modelId: "Qwen/Qwen3-0.6B",
    fit: "1.5GB — leaves the card almost free",
  },
];

export function ideasForCategory(categoryId: string): Idea[] {
  return ideas.filter((idea) => idea.categoryId === categoryId);
}
